scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'librarify_backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['librarify-php_ddd_backend-php:8030']
