services:
  # Databases
  # @todo this should be from backoffice, no librarify
  Doctrine\ORM\EntityManager:
    factory: [ MyLibrary\Librarify\Shared\Infrastructure\Doctrine\LibrarifyEntityManagerFactory, create ]
    arguments:
      - driver: '%env(LIBRARIFY_DATABASE_DRIVER)%'
        host: '%env(LIBRARIFY_DATABASE_HOST)%'
        port: '%env(LIBRARIFY_DATABASE_PORT)%'
        dbname: '%env(LIBRARIFY_DATABASE_NAME)%'
        user: '%env(LIBRARIFY_DATABASE_USER)%'
        password: '%env(LIBRARIFY_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: mylibrary.database_connection }
    public: true
